import turtle as t
t.width(10)
t.speed(0)
def treugolnik(color):
    t.pencolor('black')
    t.fillcolor(color)
    t.begin_fill()
    t.goto(50,100)
    t.goto(100,0)
    t.goto(0,0)
    t.end_fill()
    t.setheading(90)
def kvadrat(color):
    t.pencolor('black')
    t.fillcolor(color)
    t.begin_fill()
    t.fd(100)
    t.rt(90)
    t.fd(100)
    t.rt(90)
    t.fd(100)
    t.rt(90)
    t.fd(100)
    t.end_fill()
    t.setheading(90)
def krug(color):
    t.pencolor('black')
    t.fillcolor(color)
    t.begin_fill()
    t.circle(70)
    t.end_fill()
    t.setheading(90)